#%RAML 1.0 AnnotationTypeDeclaration
properties:
  usage:
    description: to understand the details about the api
    default: get
  controller:
    properties:
      protocol:
        description: the api uses HTTPS
        default: HTTPS
      url:
        description: icraftsoft.net/shopping is the url for the rest api
        default: href
      MethodUsage?:
        description: can the user use all the http methods
        type: boolean
        default: False
      AdminMethodUsage?:
        description: can admin use all the http methods
        type: boolean
        default: True

