#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: This API support oauth security
describedBy:
  headers:
    Authorization: 
      description: use have to send token value
      type: integer
  responses:
    401:
      description: unauthorized User
    403:
      description: Forbidden