#%RAML 1.0 Extension
extends: craft-onlineshopping.raml
usage: This file defines additional methods for admins
/products:
  post:
    description: creating a product
    responses:
      201:
        body:
          application/json:
            example:
              !include Examples/products.raml
      401:
        body:
          application/json:
            example:
              {
                "mesg" : "unauthorized user"
              }

  delete:
    description: admin have to send valid pwd and usersname to perform this function
    responses:
      200:
        body:
          application/json:
            example:
              {
                "msg": "product removed"
              }
      401:
        body:
          application/json:
            example:
              {
                "msg": "unauth"
              }
    