#%RAML 1.0 Overlay
usage: spanish user
extends: craft-onlineshopping.raml
documentation:
  - title: Api spec
    content: This is api spec des resource with their method, status code. The res api resource
/products: 
  description: product resource