#%RAML 1.0 DocumentationItem
title: Craft_online_shopping
content: This is craft online shopping-RAML document contains basic resorces such us product, user orderand catagory. For user application will impliment get and post HTTP methods.