#%RAML 1.0 Overlay
usage: For Amharic users
extends: craft_online_shopping.raml
documentation:
  - title: API spec
    content: This ApI spec have resources, methods and status codes.
    
/products:
  description:

  /{productid}:
    description:    

/orders:
  description: 

  /{orderid}:
    description:

/users:
  description: 
 

/catagories:
  description:          
    
