#%RAML 1.0 ResourceType
  get:
    description: get list of <<resourcePathName>>>>
    responses:
     200:
      body:
        application/json:
          example: <<exampleReference1>>

  post:
    description: <<resourcePathName>>created>> Created
    responses:
     201:
      body:
        application/json:
          example: {"msg": "<<resourcePathName>> Created"}