#%RAML 1.0 ResourceType
post:
  description: <<resourcePathName>>created>> Created
  responses:
    201:
      body:
        application/json:
          example: {"msg": "<<resourcePathName>> Created"}