#%RAML 1.0 Library
usage:
types:
  productType: !include types/product.raml
  orderType: !include types/order.raml
  postOrderType: !include types/postOrder.raml
  userType: !include types/user.raml
  postUserType: !include types/postUser.raml
  catagoryType: !include types/catagory.raml
traits:
  404response: !include traits/404Response.raml 
securitySchemes:
  security: !include securityScheme.raml
resourceTypes:
  postResponse: !include resourceTypes/postRes.raml