#%RAML 1.0 Overlay
usage: spanish user
extends: craft-online-shopping.raml
documentation:
  - title: Api spec
    content: this Api spec describes resources with their methods, status code and etc. it uses rest api resource
/products:
  description: product resource
/orders:
  description: order resource
/users:
  description: user resource
/catagories:
  description: catagory resource