#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: this Api supports Oath security
describedBy:
  headers:
    Authorization: 
     description: user have to send token for any request
     type: string
  queryParameters:
    access_token:
      description: user have to send valid access token
      type: integer
      example: 4567893
  responses:
    401:
      description: unauthorized user
    403:
      description: forbidden
        