#%RAML 1.0 NamedExample
[{
  "orderid": 51,
  "userid": 1,
  "addressid": 201,
  "discountid": 6,
  "Created": "2021-04-04 12:39:30",
  "modified": "2021-04-04 12:39:30",
  "status": shipped,
  "amount": 550
}, {
  "orderid": 52,
  "userid": 2,
  "addressid": 208,
  "discountid": 6,
  "Created": "2021-05-04 12:39:30",
  "modified": "2021-05-04 12:39:30",
  "status": delayed,
  "amount": 699
}


]