#%RAML 1.0 NamedExample
[
  {
      "name": "Dell",
      "description": "Dell laptop",
      "price": 3456,
      "productId": 123,
      "categoryID": 12,
      "vedio_url": "dell.com"
  },{
      "name": "lenovo",
      "description": "lenovo laptop",
      "price": 1599,
      "productId": 122,
      "categoryID": 11,
      "vedio_url": "lenovo.com"
  }
  ]