#%RAML 1.0 NamedExample
[{
  "userid": 9,
  "email": "helloworld@gmail.com",
  "name": "Mary Anne",
  "date_of_birth": 1994-08-07,
  "phone": 4151234567,
  "password": helloworld,
  "date_joined": 2019-05-07,
  "modified": 2020-06-12,
  "type": 80,
  "deleted": false

},{
  "userid": 7,
  "email": "hello@gmail.com",
  "name": "Jhon Smith",
  "date_of_birth": 1998-08-07,
  "phone": 5101234567,
  "password": helloworld,
  "date_joined": 2020-05-07,
  "modified": 2021-06-12,
  "type": 7,
  "deleted": false

}

]