#%RAML 1.0 NamedExample
[
  {
"orderId": 200,
"userID": 111,
"address": "123, craft St, NC",
"product_name": "Dell",
"created": 2021-04-10T06:35:00,
"status": "Shipped",
"amount": 3456
},
 {
"orderId": 201,
"userID": 112,
"address": "123, craft St, NC",
"product_name": "Mac Book",
"created": 2021-04-10T06:35:00,
"status": "Shipped",
"amount": 3456
},
 {
"orderId": 203,
"userID": 113,
"address": "123, craft St, NC",
"product_name": "HP",
"created": 2021-04-10T06:35:00,
"status": "Shipped",
"amount": 3456
},
 {
"orderId": 204,
"userID": 114,
"address": "123, craft St, NC",
"product_name": "Acer",
"created": 2021-04-10T06:35:00,
"status": "Shipped",
"amount": 3456
},
 {
"orderId": 205,
"userID": 114,
"address": "123, craft St, NC",
"product_name": "HP",
"created": 2021-04-10T06:35:00,
"status": "Shipped",
"amount": 3456
}
]