#%RAML 1.0 NamedExample
[
  {
	"productId": 1,
	"categoryID": 11,
	"product_name": "Dell",
	"description": "Dell laptop",
	"price": 3456,
	"vidio_url": "dell.com"
},
{
	"productId": 2,
	"categoryID": 11,
	"product_name": "Dell",
	"description": "Dell laptop",
	"price": 3456,
	"vidio_url": "www.dell.com"
},
 {
	"productId": 3,
	"categoryID": 12,
	"product_name": "HP",
	"description": "HP laptop",
	"price": 3456,
	"vidio_url": "www.hp.com"
},
{
	"productId": 4,
	"categoryID": 12,
	"product_name": "HP",
	"description": "HP laptop",
	"price": 3456,
	"vidio_url": "www.hp.com"
},
{
	"productId": 5,
	"categoryID": 13,
	"product_name": "MacBook",
	"description": "Apple laptop",
	"price": 3456,
	"vidio_url": "www.apple.com"
},
{
	"productId": 6,
	"categoryID": 13,
	"product_name": "MacBook",
	"description": "Apple laptop",
	"price": 3456,
	"vidio_url": "www.apple.com"
}
]