#%RAML 1.0 NamedExample
[
{
	"productId": 7,
	"categoryID": 14,
	"product_name": "Acer 7",
	"description": "Acer laptop",
	"price": 3456,
	"vidio_url": "www.acer.com"
},

{
	"productId": 8,
	"categoryID": 14,
	"product_name": "Acer ",
	"description": "Acer laptop",
	"price": 3456,
	"vidio_url": "www.acer.com"
}
    ] 