#%RAML 1.0 NamedExample
[{
  userID: 111,
  userName: "John Craft",
  address: "123, wwe st, Ca",
  phone_number: "12345678",
  email: "craft@example.com"
  },
  {
  userID: 112,
  userName: "John Cena",
  address: "123, wwe st, Ca",
  phone_number: "12345678",
  email: "cena@example.com"
  },
  {
  userID: 113,
  userName: "John Class",
  address: "123, wwe st, Ca",
  phone_number: "12345678",
  email: "class@example.com"
  },
  {
  userID: 114,
  userName: "John Example",
  address: "123, wwe st, Ca",
  phone_number: "12345678",
  email: "example@example.com"
  }
]