#%RAML 1.0 NamedExample
  [{
               "categoryid" : 1254,
                "name": "dell"},
                {
               "categoryid" : 1254,
                "name": "dell"},
                {
               "categoryid" : 1254,
                "name": "dell"}
              ]