#%RAML 1.0 NamedExample
  [
            {
            "orderId" : 132,
            "userId" : 123,
            "addressId" : 201,
            "discountId" : 3,
            "created" : "2019-05-12",
            "modified" : "2019-05-12",
            "status" : "shipped",
            "amount" : 550
          },
            {
            "orderId" : 132,
            "userId" : 123,
            "addressId" : 201,
            "discountId" : 3,
            "created" : "2019-05-12",
            "modified" : "2019-05-12",
            "status" : "shipped",
            "amount" : 550
          }]