#%RAML 1.0 NamedExample
[
 {
  "firstName": John,
  "lastName": Doe,
  "age": 18,
  "address": "1234 win way dr", 
  "city": "decatur",
  "state": "Georgia",
  "postalCode": 12345,

},
{
   "firstName": John,
  "lastName": Doe,
  "age": 18,
  "address": "1234 win way dr", 
  "city": "decatur",
  "state": "Georgia",
  "postalCode": 12345
 }
]