#%RAML 1.0 DataType
description: data type for orders
type: object
properties: 
  orderId: integer
  userID: integer
  address: string
  product_name: string
  created ?: datetime
  status: string
  amount: integer
