#%RAML 1.0 DataType
description: users data type
type: object
properties:
  userID: integer
  userName: string
  address: string
  phone_number: string
  email: 
    type: string
    # pattern: ^(.+\@\D+\.\D+)$


